sudo: required

services:
    - docker

install:
    - docker build -t dotfiles .

script:
    - docker run dotfiles bash -c "./install.sh -i install -n -o"

after_success:
    - docker build -t codecoverage .
    - sudo apt-get install wget
    - docker run codecoverage bash -c "sudo apt-get install -y
        libcurl4-openssl-dev libelf-dev libdw-dev cmake wget curl zlib1g-dev"
    - ci_env=`bash <(curl -s https://codecov.io/env)`
    - docker run $ci_env codecoverage bash -c "bash ./code_coverage.sh"
